spring.application.name=walletX
spring.datasource.url=jdbc:postgresql://localhost:5432/walletx
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger UI Configuration
springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.path=/api/v1/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha